#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN K22 [get_ports sys_clk_p]
set_property PACKAGE_PIN K23 [get_ports sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_n]
############## fan define##################
set_property IOSTANDARD LVCMOS33 [get_ports fan_pwm]
set_property PACKAGE_PIN Y16 [get_ports fan_pwm]


##############DA1 define##################
set_property PACKAGE_PIN A10 [get_ports {da1_data[13]}]
set_property PACKAGE_PIN B10 [get_ports {da1_data[12]}]
set_property PACKAGE_PIN B11 [get_ports {da1_data[11]}]
set_property PACKAGE_PIN C11 [get_ports {da1_data[10]}]
set_property PACKAGE_PIN E10 [get_ports {da1_data[9]}]
set_property PACKAGE_PIN E11 [get_ports {da1_data[8]}]
set_property PACKAGE_PIN A9  [get_ports {da1_data[7]}]
set_property PACKAGE_PIN B9  [get_ports {da1_data[6]}]
set_property PACKAGE_PIN D10 [get_ports {da1_data[5]}]
set_property PACKAGE_PIN D11 [get_ports {da1_data[4]}]
set_property PACKAGE_PIN C9  [get_ports {da1_data[3]}]
set_property PACKAGE_PIN D9  [get_ports {da1_data[2]}]
set_property PACKAGE_PIN F9  [get_ports {da1_data[1]}]
set_property PACKAGE_PIN F10 [get_ports {da1_data[0]}]
set_property PACKAGE_PIN G9  [get_ports {da1_wrt}]
set_property PACKAGE_PIN G10 [get_ports {da1_clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_clk}]


##############DA2 define##################
set_property PACKAGE_PIN H9  [get_ports {da2_clk}]
set_property PACKAGE_PIN J9  [get_ports {da2_wrt}]
set_property PACKAGE_PIN J10 [get_ports {da2_data[13]}]
set_property PACKAGE_PIN J11 [get_ports {da2_data[12]}]
set_property PACKAGE_PIN G11 [get_ports {da2_data[11]}]
set_property PACKAGE_PIN H11 [get_ports {da2_data[10]}]
set_property PACKAGE_PIN K9  [get_ports {da2_data[9]}]
set_property PACKAGE_PIN K10 [get_ports {da2_data[8]}]
set_property PACKAGE_PIN B12 [get_ports {da2_data[7]}]
set_property PACKAGE_PIN C12 [get_ports {da2_data[6]}]
set_property PACKAGE_PIN E12 [get_ports {da2_data[5]}]
set_property PACKAGE_PIN E13 [get_ports {da2_data[4]}]
set_property PACKAGE_PIN F12 [get_ports {da2_data[3]}]
set_property PACKAGE_PIN G12 [get_ports {da2_data[2]}]
set_property PACKAGE_PIN A12 [get_ports {da2_data[1]}]
set_property PACKAGE_PIN A13 [get_ports {da2_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {da2_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[0]}]